apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dzhunli/argocd_tests.git
    targetRevision: main 
    path: applications/helloworld
    helm:
      releaseName: helloapp
      values: |
        service:
          type: NodePort
          nodePort: 8089
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: examples
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

