apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dzhunli/argocd_tests.git
    targetRevision: main 
    path: manifests/helloworld
    helm:
      releaseName: helloapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

